In [8]:
from pathlib import Path
from typing import Final, Optional

import matplotlib.pyplot as plt
import numpy as np
import numpy.typing as npt
import polars as pl
from joblib import Memory

from src.config.constants import Product
from src.processing.dataset_spec import DatasetSpec
from src.processing.orderbook import OrderBookDataProcessor, OrderBookDataset
from src.research.black_scholes import BlackScholesCall

memory = Memory("./cache")

VELVETFRUIT_EXTRACT = Product.VELVETFRUIT_EXTRACT
VEV_OPTIONS_PREF: Final[str] = "VEV_"
ROUND: Final[int] = 3
DAY: Final[int] = 0

DATASET: Final[DatasetSpec] = DatasetSpec(ROUND, DAY)
ORDERBOOK_CSV_FILE: Final[Path] = DATASET.prices()
RAW_UNDERLYING_ORDERBOOK_DATA: Final[OrderBookDataProcessor] = OrderBookDataset(
    ORDERBOOK_CSV_FILE
).for_product(VELVETFRUIT_EXTRACT)
RAW_OPTIONS_ORDERBOOK_DATA: Final[OrderBookDataProcessor] = OrderBookDataset(
    ORDERBOOK_CSV_FILE
).for_product("VEV_")

underlying_orderbook_data = (
    RAW_UNDERLYING_ORDERBOOK_DATA.clean()
    .build()
    .select(["timestamp", "mid_price"])
    .rename({"mid_price": "spot_price"})
)
options_orderbook_data = (
    RAW_OPTIONS_ORDERBOOK_DATA.clean()
    .add_strikes_col()
    .add_microstructure_features()
    .add_price_features()
    .add_depth_features()
    .build()
).join(underlying_orderbook_data, on="timestamp", how="left")

BS: Final[BlackScholesCall] = BlackScholesCall(r=0, T_days=5)

In [9]:
options_orderbook_data

shape: (100_000, 25)
┌───────────┬──────────┬────────────┬────────────┬───┬────────────┬────────────┬───────┬───────────┐
│ timestamp ┆ product  ┆ bid_price_ ┆ bid_volume ┆ … ┆ microprice ┆ microprice ┆ depth ┆ spot_pric │
│ ---       ┆ ---      ┆ 1          ┆ _1         ┆   ┆ ---        ┆ _dev       ┆ ---   ┆ e         │
│ i64       ┆ str      ┆ ---        ┆ ---        ┆   ┆ f64        ┆ ---        ┆ i64   ┆ ---       │
│           ┆          ┆ i64        ┆ i64        ┆   ┆            ┆ f64        ┆       ┆ f64       │
╞═══════════╪══════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════╪═══════════╡
│ 0         ┆ VEV_5400 ┆ 22         ┆ 25         ┆ … ┆ 23.0       ┆ 0.0        ┆ 50    ┆ 5250.0    │
│ 0         ┆ VEV_6500 ┆ 0          ┆ 16         ┆ … ┆ 0.5        ┆ 0.0        ┆ 32    ┆ 5250.0    │
│ 0         ┆ VEV_5500 ┆ 8          ┆ 25         ┆ … ┆ 8.5        ┆ 0.0        ┆ 50    ┆ 5250.0    │
│ 0         ┆ VEV_5200 ┆ 100        ┆ 19         ┆ … ┆ 102.28     ┆ 0.78       ┆ 25    ┆ 5250.0    │
│ 0         ┆ VEV_5300 ┆ 52         ┆ 6          ┆ … ┆ 52.387097  ┆ -0.612903  ┆ 31    ┆ 5250.0    │
│ …         ┆ …        ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …     ┆ …         │
│ 999900    ┆ VEV_5000 ┆ 247        ┆ 23         ┆ … ┆ 251.181818 ┆ 1.181818   ┆ 33    ┆ 5244.0    │
│ 999900    ┆ VEV_4000 ┆ 1234       ┆ 14         ┆ … ┆ 1244.0     ┆ 0.0        ┆ 28    ┆ 5244.0    │
│ 999900    ┆ VEV_5100 ┆ 162        ┆ 23         ┆ … ┆ 164.787879 ┆ 0.787879   ┆ 33    ┆ 5244.0    │
│ 999900    ┆ VEV_6000 ┆ 0          ┆ 21         ┆ … ┆ 0.5        ┆ 0.0        ┆ 42    ┆ 5244.0    │
│ 999900    ┆ VEV_4500 ┆ 736        ┆ 10         ┆ … ┆ 744.0      ┆ 0.0        ┆ 20    ┆ 5244.0    │
└───────────┴──────────┴────────────┴────────────┴───┴────────────┴────────────┴───────┴───────────┘

In [10]:
options_orderbook_data = options_orderbook_data.with_columns(
    [(pl.col("spot_price") / pl.col("strike_price")).log().alias("log_moneyness")]
)

In [21]:
@memory.cache
def get_iv_vector() -> list[Optional[float]]:
    C_market_vector: npt.NDArray[np.float64] = options_orderbook_data[
        "microprice"
    ].to_numpy()
    K_vector: npt.NDArray[np.float64] = options_orderbook_data[
        "strike_price"
    ].to_numpy()
    S_vector: npt.NDArray[np.float64] = options_orderbook_data["spot_price"].to_numpy()

    IV_vector = [
        BS.implied_vol(C_market=c, K=k, S=s)
        for c, k, s in zip(C_market_vector, K_vector, S_vector)
    ]

    return IV_vector


IV_vector = get_iv_vector()

In [17]:
options_orderbook_data = options_orderbook_data.with_columns(
    pl.Series(name="IV", values=IV_vector)
).drop_nulls("IV")
options_orderbook_data

shape: (96_017, 27)
┌───────────┬──────────┬─────────────┬────────────┬───┬───────┬────────────┬────────────┬──────────┐
│ timestamp ┆ product  ┆ bid_price_1 ┆ bid_volume ┆ … ┆ depth ┆ spot_price ┆ log_moneyn ┆ IV       │
│ ---       ┆ ---      ┆ ---         ┆ _1         ┆   ┆ ---   ┆ ---        ┆ ess        ┆ ---      │
│ i64       ┆ str      ┆ i64         ┆ ---        ┆   ┆ i64   ┆ f64        ┆ ---        ┆ f64      │
│           ┆          ┆             ┆ i64        ┆   ┆       ┆            ┆ f64        ┆          │
╞═══════════╪══════════╪═════════════╪════════════╪═══╪═══════╪════════════╪════════════╪══════════╡
│ 0         ┆ VEV_5400 ┆ 22          ┆ 25         ┆ … ┆ 50    ┆ 5250.0     ┆ -0.028171  ┆ 0.303428 │
│ 0         ┆ VEV_6500 ┆ 0           ┆ 16         ┆ … ┆ 32    ┆ 5250.0     ┆ -0.213574  ┆ 0.677302 │
│ 0         ┆ VEV_5500 ┆ 8           ┆ 25         ┆ … ┆ 50    ┆ 5250.0     ┆ -0.04652   ┆ 0.303375 │
│ 0         ┆ VEV_5200 ┆ 100         ┆ 19         ┆ … ┆ 25    ┆ 5250.0     ┆ 0.009569   ┆ 0.305918 │
│ 0         ┆ VEV_5300 ┆ 52          ┆ 6          ┆ … ┆ 31    ┆ 5250.0     ┆ -0.009479  ┆ 0.303469 │
│ …         ┆ …        ┆ …           ┆ …          ┆ … ┆ …     ┆ …          ┆ …          ┆ …        │
│ 999900    ┆ VEV_5000 ┆ 247         ┆ 23         ┆ … ┆ 33    ┆ 5244.0     ┆ 0.047647   ┆ 0.299366 │
│ 999900    ┆ VEV_4000 ┆ 1234        ┆ 14         ┆ … ┆ 28    ┆ 5244.0     ┆ 0.27079    ┆ 0.423225 │
│ 999900    ┆ VEV_5100 ┆ 162         ┆ 23         ┆ … ┆ 33    ┆ 5244.0     ┆ 0.027844   ┆ 0.292519 │
│ 999900    ┆ VEV_6000 ┆ 0           ┆ 21         ┆ … ┆ 42    ┆ 5244.0     ┆ -0.134675  ┆ 0.450465 │
│ 999900    ┆ VEV_4500 ┆ 736         ┆ 10         ┆ … ┆ 20    ┆ 5244.0     ┆ 0.153007   ┆ 0.237736 │
└───────────┴──────────┴─────────────┴────────────┴───┴───────┴────────────┴────────────┴──────────┘

In [18]:
options_orderbook_data["IV"].describe()

shape: (9, 2)
┌────────────┬──────────┐
│ statistic  ┆ value    │
│ ---        ┆ ---      │
│ str        ┆ f64      │
╞════════════╪══════════╡
│ count      ┆ 96017.0  │
│ null_count ┆ 0.0      │
│ mean       ┆ 0.372564 │
│ std        ┆ 0.138282 │
│ min        ┆ 0.229798 │
│ 25%        ┆ 0.292287 │
│ 50%        ┆ 0.300403 │
│ 75%        ┆ 0.431613 │
│ max        ┆ 1.123659 │
└────────────┴──────────┘

In [19]:
options_features_data = options_orderbook_data.select(
    ["timestamp", "strike_price", "spot_price", "mid_price", "log_moneyness", "IV"]
)
options_features_data

shape: (96_017, 6)
┌───────────┬──────────────┬────────────┬───────────┬───────────────┬──────────┐
│ timestamp ┆ strike_price ┆ spot_price ┆ mid_price ┆ log_moneyness ┆ IV       │
│ ---       ┆ ---          ┆ ---        ┆ ---       ┆ ---           ┆ ---      │
│ i64       ┆ i64          ┆ f64        ┆ f64       ┆ f64           ┆ f64      │
╞═══════════╪══════════════╪════════════╪═══════════╪═══════════════╪══════════╡
│ 0         ┆ 5400         ┆ 5250.0     ┆ 23.0      ┆ -0.028171     ┆ 0.303428 │
│ 0         ┆ 6500         ┆ 5250.0     ┆ 0.5       ┆ -0.213574     ┆ 0.677302 │
│ 0         ┆ 5500         ┆ 5250.0     ┆ 8.5       ┆ -0.04652      ┆ 0.303375 │
│ 0         ┆ 5200         ┆ 5250.0     ┆ 101.5     ┆ 0.009569      ┆ 0.305918 │
│ 0         ┆ 5300         ┆ 5250.0     ┆ 53.0      ┆ -0.009479     ┆ 0.303469 │
│ …         ┆ …            ┆ …          ┆ …         ┆ …             ┆ …        │
│ 999900    ┆ 5000         ┆ 5244.0     ┆ 250.0     ┆ 0.047647      ┆ 0.299366 │
│ 999900    ┆ 4000         ┆ 5244.0     ┆ 1244.0    ┆ 0.27079       ┆ 0.423225 │
│ 999900    ┆ 5100         ┆ 5244.0     ┆ 164.0     ┆ 0.027844      ┆ 0.292519 │
│ 999900    ┆ 6000         ┆ 5244.0     ┆ 0.5       ┆ -0.134675     ┆ 0.450465 │
│ 999900    ┆ 4500         ┆ 5244.0     ┆ 744.0     ┆ 0.153007      ┆ 0.237736 │
└───────────┴──────────────┴────────────┴───────────┴───────────────┴──────────┘

In [20]:
import plotly.graph_objects as go

df = options_features_data.sort("timestamp")

timestamps = df["timestamp"].unique().to_list()

# (optional but recommended if many timestamps)
timestamps = timestamps[::10]

# initial snapshot
t0 = timestamps[0]
snap0 = df.filter(pl.col("timestamp") == t0)
snap0 = snap0.filter(
    (pl.col("IV") > 0.005)
    & (pl.col("IV") < 1.0)
    & (pl.col("log_moneyness").abs() < 0.2)
)

fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=snap0["log_moneyness"].to_numpy(), y=snap0["IV"].to_numpy(), mode="markers"
    )
)

# build slider steps
steps = []
for t in timestamps:
    snap = df.filter(pl.col("timestamp") == t)

    steps.append(
        dict(
            method="update",
            args=[
                {"x": [snap["log_moneyness"].to_numpy()], "y": [snap["IV"].to_numpy()]}
            ],
            label=str(t),
        )
    )

# attach slider
fig.update_layout(
    sliders=[{"active": 0, "steps": steps}],
    xaxis_title="log moneyness",
    yaxis_title="IV",
    title="Vol Smile Over Time",
)

fig.show()